### PR TITLE
Add ability to override region in provider configuration

### PR DESCRIPTION
**Pull request by bronislav**

### CODE REVIEW

**Comment by antonbabenko** [comment]
I don't think this PR is needed, because you can set AWS_DEFAULT_REGION env variable to make Terraform to manage resources in specific region. More info - https://www.terraform.io/docs/providers/aws/

**Comment by bronislav** [comment]
@antonbabenko There are currently long standing bug which don't allow to pass provider parameter to module. This is needed when you want to use several providers in the same config (one for each region).

And the only workaround to do this is to instantiate own provider in the module and pass parameters to the module through variables.

**Comment by antonbabenko** [comment]
I think this look like a hack. If we merge this code that it will not respect env variable AWS_DEFAULT_REGION which is set and used by other terraform resources already.

I think, if you need to make resources in several regions the best way would be if you run same terraform commands with different env variables.

**Comment by bronislav** [comment]
OK.

**Pull request closed without merging**
